// User
export const SET_USERNAME = 'SET_USERNAME';

// Game
export const SAVE_GAME = 'SAVE_GAME';
export const SAVE_GAME_SUCCESS = 'SAVE_GAME_SUCCESS';

export const GET_SCOREBOARD_STARTED = 'GET_SCOREBOARD_STARTED';
export const GET_SCOREBOARD_RECEIVED_DATA = 'GET_SCOREBOARD_RECEIVED_DATA';
